elasticsearch:
  build: elasticsearch/
  container_name: elasticsearch
  volumes:
   - /usr/share/elasticsearch/data:/usr/share/elasticsearch/data
  ports:
    - "9200:9200"
    - "9300:9300"
kibana:
  build: kibana/
  container_name: kibana
  ports:
    - "5601:5601"
  links:
    - elasticsearch
kibana3:
  build: kibana3/
  container_name: kibana3
  ports:
    - "8083:80"
